- docker/server/entrypoint.sh
Removed --sync from docker/server/entrypoint.sh
- Resolve #50
> I50 Remove sync from docker entrypoint

- server/api/subteam/tests.py
> create test for subteam endpoint

- server/api/team/tests.py
Add unit tests for team endpoint
no documentation needed for unit test
-
- Resolve #70 
- Resolve #70
> I70 create django automated tests for team endpoint

- .github/workflows/docker-build.yml
> I31 continuous deployment automatic deployment of docker images to dockerhub

- client/src/assets/base.css
Removed light mode stuff from base.css so it defaults
- Resolve #97
> i97 Fix light mode

- client/src/App.vue
- client/src/views/EventsView.vue
> NONE fix input issue

- .github/pull_request_template.md
- .vscode/extensions.json
- .vscode/settings.json
- client/.vscode/extensions.json
* more important extensions in `extensions.json`
* adds paths to various config files so that relevant extensions can find them (`.vscode/settings.json`)
* adds the PR request template to the repo so it can be found by third parties (e.g. Github vscode extension)
NA
this doesn't affect the actual app
> QOL improvements

- client/src/components/ConsentModal.vue
Updated the wording of the privacy statement when registering to be for multiple events rather than a single event.
- Resolve #126
> i126 Consent info modification

- client/src/components/teams/EditTeamInfo.vue
- client/src/components/teams/TeamDashboard.vue
Changed text and icons to black instead of blue
> Team Dashboard Font & Icon Colour Fix

- server/api/users/tests.py
add unit test for get_user endpoint only
the only function that has not been tested is get_user endpoint hence this pr will only address that issue
- Resolve #56
> i56-automated_testing_for_user_model

- client/src/components/MileageModal.vue
- client/src/types/mileage.ts
* Create mileage type
* Pass input data to backend
- Resolve #120
> I120 connect mileage modal to backend

- client/src/components/MileageGraph.vue
- client/src/stores/mileage.ts
- client/src/types/mileage.ts
- client/src/views/DashboardView.vue
- client/yarn.lock
- yarn lock had some merge conflicts
> Fix yarn lock

- client/src/components/SignUpModal.vue
see title
NA
NA
- Resolve #162
> i162 switch to login modal after signup

- client/src/components/teams/CreateOrJoinTeam.vue
- client/src/components/teams/EditTeamInfo.vue
- client/src/components/teams/NewTeamModal.vue
fixed modals to match event page
added fullscreen functionality to both modals and fixed bug where modal covers left side of screen on ipad
fixed navbar and spacing of text on create or join team page
- Resolve #155
> I155 update team modals UI

- .env.dev
- client/src/stores/team.ts
- client/src/utils/server.ts
- server/api/settings.py
> i167 move_backend_base_url_to_env_file

- client/src/components/LoginModal.vue
- client/src/components/SignUpModal.vue
- client/src/stores/modal.ts
- client/src/views/AboutView.vue
* automatically have consent checked
* fix **breaking** issues caused by my #160 (sry)
* related code is working correctly and should cleaner
> i172 fixes + automatically have consent checked

- .github/workflows/backend-testing.yml
- client/src/components/EventCard.vue
- client/src/components/MileageModal.vue
- client/src/stores/user.ts
- client/src/views/EventsView.vue
- client/src/views/UserSettingsView.vue
- server/api/team/tests.py
> i161 remove add event button for non team admin

- client/src/components/ChangePasswordModal.vue
- client/src/components/EventsModal.vue
- client/src/components/Footer.vue
- client/src/components/LoginModal.vue
- client/src/components/MileageModal.vue
- client/src/components/NavbarComponents.vue
- client/src/components/PopupDialog.vue
- client/src/components/SignUpModal.vue
- client/src/components/teams/EditTeamInfo.vue
- client/src/components/teams/NewTeamModal.vue
- client/src/views/AboutView.vue
Improved score by mostly adding aria roles to specific elements
NA
- [x ] The pull request title has an issue number
Background and foreground colors do not have a sufficient contrast ratio is the main problem. 
- Resolve #108
> I108 improve website accessibility score

- client/src/views/DashboardView.vue
- all required changes
- Resolve #189
> i189 - all changes to padding, size of settings icon and adding container

- client/src/components/teams/EditTeamInfo.vue
- change the edit team modal to contain the right pre-text so the user can understand whats going on
- Resolve #190
> i190 - change to team name

- client/src/components/teams/TeamDashboard.vue
- client/src/views/TeamsPageView.vue
- made graph load up on page load like requested
- Resolve #193
> i193 - graph section

- client/src/components/LoginModal.vue
- client/src/components/ReloadPWA.vue
- client/src/components/SignUpModal.vue
- client/src/components/teams/CreateOrJoinTeam.vue
- client/src/components/teams/EditTeamInfo.vue
- client/src/components/teams/NewTeamModal.vue
- client/src/components/teams/TeamDashboard.vue
- client/src/router/index.ts
- client/src/stores/team.ts
- client/src/stores/user.ts
- client/src/types/user.ts
- client/src/utils/server.ts
- client/src/utils/useNullableStorage.ts
- client/src/views/TeamsPageView.vue
* it should no longer require a reload to be able to do stuff that requires auth
~there was also another issue that when logging out it doesn't clear the store. this maybe fixes that idk tho~ fixed
> fix unauthorised after login without reload

- client/src/views/DashboardView.vue
* Made the progress bar labels also show the amount of kilometres achieved so far
* Removed v-spacers in the header, which also has the benefit of the title being slower to take up additional lines as the width of the window is reduced
> show progress on challenges

- client/src/components/teams/TeamDashboard.vue
* made team page display the user's travel icon
- Resolve #201
> made team page display the user's travel icon

- client/src/views/DashboardView.vue
* Show username in dashboard rather than first name
- Resolve #205
> show username in dashboard rather than first name

- client/src/components/SignUpModal.vue
> Remove unnecessary error message when signing up incorrectly

- server/api/settings.py
> Added CSRF trusted origins

- client/src/views/EventsView.vue
* Every second event has background colour rgb(245,245,245)
- Resolve #234
> change colour of event cards

- client/src/components/ChangePasswordModal.vue
- client/src/components/SignUpModal.vue
- client/src/views/UserSettingsView.vue
- made so active avatar actually works on settings page
- made so reset password component looks half decent
- Resolve #227
> i227 fix reset passwrod modal and something else

- server/api/auth/serializers.py
* Changed the serializer so that blank first and last names aren't accepted in the signup modal
- Resolve #221
> ensure first and last names cannot be blank during signup

- client/src/components/teams/TeamDashboard.vue
* Should close issues #212 and #236 
- Resolve #212
> team info updates without refresh, and use confirm button to delete team

- client/index.html
Changed title in `index.html` so it doesn't say `Vite App` when loading.
- Resolve #250
> i250 change title

- client/src/components/SignUpModal.vue
added the click functionality for the second "Already Have an Account?" button that was present in the first
- Resolve #239
> i239-switch_from_signup_page_2_to_login_modal

- client/src/views/EventsView.vue
added the same banner from the challenge page to the events page
- Resolve #225
> i225-add_banner_to_events_page

- client/src/components/EventCard.vue
- client/src/utils/date.ts
Added a util function in utils/date.ts that converts date format. Applied it to the events card vue.
- Resolve #246
> events-date-working

- client/src/components/ChangePasswordModal.vue
- client/src/components/ConfirmButton.vue
- client/src/components/EventsModal.vue
- client/src/components/LoginModal.vue
- client/src/components/MileageModal.vue
- client/src/components/SignUpModal.vue
- client/src/components/teams/CreateOrJoinTeam.vue
- client/src/components/teams/NewTeamModal.vue
- client/src/components/teams/SubTeamsModal.vue
- client/src/components/teams/TeamDashboard.vue
- client/src/views/UserSettingsView.vue
Added loading icon to all appropriate buttons
- Resolve #230
> I230 add loading icon to all submit buttons

- client/src/components/SignUpModal.vue
- client/src/views/UserSettingsView.vue
fixed the deselection bug for the avatar and mode on sign up modal and I think settings page? I applied the same fix but I can't register a user to test if it works there. if there's already a registered test user lmk the details and i'll give that a go too.
- Resolve #194
> i194-fix_avatar_and_travel_method_selection_bug

- client/src/components/ChallengeCompletePopupModal.vue
- client/src/views/DashboardView.vue
* Added a popup modal for challenge completion
* The popup appears on the user dashboard when a challenge has been completed
* This only occurs when mileage added causes the challenge to be completed and won't occur again for that challenge
- Resolve #188
> I188 display message when challenge is achieved

- client/src/components/teams/CreateOrJoinTeam.vue
- client/src/components/teams/EditTeamInfo.vue
- client/src/components/teams/NewTeamModal.vue
- client/src/components/teams/TeamDashboard.vue
- client/src/stores/team.ts
- server/api/users/tests.py
- server/api/users/views.py
create handler when user attempts to join nonexistent team in the backend and create alert for the front end
- Resolve #231
> I231 show error message when trying to join a nonexistent team

- client/src/components/MileageGraph.vue
- client/src/components/teams/TeamDashboard.vue
* Made the chips at the top of the graph wrap if the screen becomes narrow
* Put graph inside its own v-row, which keeps the chevron button above the graph
* Used a v-container around the around the daily kms section
- Resolve #213
> I213 team page graph causes hamburger menu to move off screen on mobile

- client/src/components/EventCard.vue
* Added some styles to the v-card-title so that the title will wrap
- Resolve #214
> I214 event names with long titles cause the chips to be cut off on mobile

- server/api/settings.py
> Hot Fix Email

- client/src/views/ChallengeView.vue
> i276 challenge title

- client/src/components/teams/TeamDashboard.vue
* The button to leave a joined team now has a conformation popup
- Resolve #260
> Add confirm popup to leave team

- client/src/stores/mileage.ts
- server/api/mileage/test_authenticated.py
- server/api/mileage/views.py
* Add back the original logic by Jasper for calculating challenge period mileage, plus a few tweaks
> Fix challenge mileage

- client/src/views/DashboardView.vue
* User dashboard now shows user's total mileage rather than the user's team
> use user mileage rather than team mileage

- README.md
- client/src/components/teams/SubTeamsModal.vue
- client/src/stores/subTeam.ts
- documentation/docs/admin/accounts.md
- documentation/docs/backend/email.md
- documentation/docs/backend/endpoints.md
- documentation/docs/index.md
- done but i forgot why i needed to update readme?
Resolve #283 
Resolve #281 
- Resolve #281
> I281 clean up documentation and readme

- client/src/components/MileageModal.vue
> increment by 0.1
